### ISSUE TITLE
Specified folder/zip file does not contain a valid library

### ISSUE THREAD

**Issue by DR2727** [nootropicdesign/digit-shield#1]
IDE V. 1.8.5
Windows 10

Specified folder/zip file does not contain a valid library.

Downloaded the .ZIP file from here. Went to install it into my IDE as I've done many times before. Not working.

**Comment by nootropicdesign** [comment]
When you download a zip file from GitHub, you are downloading the repository. Unzip it and install the DigitShield folder in your Arduino libraries folder.
